FROM public.ecr.aws/ubuntu/ubuntu:16.04

# just to invalidate cache
ARG BUILDDATE=99999999

ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir -p /build \
  && apt-get update \
  && apt-get install -y --no-install-recommends lsb-release tzdata debhelper dh-make devscripts gnupg2 vim equivs
RUN mkdir -p -m700 /root/.gnupg

