FROM mirror.gcr.io/library/debian:bookworm

# just to invalidate cache
ARG BUILDDATE=99999999

ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir -p /build \
  && apt-get update \
  && apt-get install -y --no-install-recommends lsb-release tzdata debhelper dh-make devscripts gnupg2 vim equivs fakeroot
RUN mkdir -p -m700 /root/.gnupg
